### ISSUE TITLE
Russian translation and maintainer

### ISSUE THREAD

**Issue by lorien** [jlevy/the-art-of-command-line#103]
Hey,
Do not you mind I'll make russian translation of this document?
Will you accept my pull-request with README-ru.md file?

**Comment by jlevy** [comment]
Yes, that would be great. Will you also be able to maintain it as the English one evolves?

**Comment by antipin** [comment]
I'd like to participate too
@lorien what do you think?

**Comment by jlevy** [comment]
@antipin for sure, help always welcome! @lorien if you have something, give a PR? Whichever of you has time to PR a first version, please do and then we can improve it.

Would be great if one person can sign also agree to maintain by reviewing changes and PRs. Thank you!

**Comment by lorien** [comment]
Hi, guys. I've tried to translate the document and I've found that it requires much more time I thought. So, @antipin please feel free to start translating the document, I'll contribute to your translation when I'll have some free time.

**Comment by antipin** [comment]
Ok, I've started my translation [here](https://github.com/antipin/the-art-of-command-line/blob/master/README-ru.md), if anyone russian-speaking would like to join – you are welcome!

**Comment by jlevy** [comment]
Thanks to @olegberman we have a full translation now!
@antipin @lorien -- would be great if you can review. As usual, PR/file issues if you see anything that can be improved. Thanks!

**Comment by olegberman** [comment]
Hey @antipin and other comrades!

If you guys could revise my translation it would be great. Possibly a few sentences need to be rephrased to sound more natural. Special thanks to @jlevy for creating an awesome guide!

**Comment by sn00p** [comment]
I've polished this a little. Please see pull request. Good work, guys! 
Though more work has to be done to make this more "russian".

**Comment by jlevy** [comment]
@olegberman seems like you've taken on coordinating this so closing this issue. :)

**Comment by olegberman** [comment]
👍
