### ISSUE TITLE
Consider adding duviz (makes du more visual) 

### ISSUE THREAD

**Issue by soxofaan** [jlevy/the-art-of-command-line#108]
consider adding https://github.com/soxofaan/duviz

(disclaimer: I'm the author of that tool)

**Comment by jlevy** [comment]
It looks useful but not sure it's "essential" enough for this guide. Also, I only include items that are installable in a standard way, like apt-get or pip.

Have you considered publishing your package to pypi? It's not hard.

Once you do that, I'd suggest PRing it to https://github.com/alebcay/awesome-shell

Thanks for the suggestion!
