### ISSUE TITLE
zh: Proper spacing between English and Chinese words

### ISSUE THREAD

**Issue by bryandeng** [jlevy/the-art-of-command-line#126]
When typesetting mixed English-Chinese text, it's suggested to add space between English and Chinese words. For example, `使用 Github 来做` instead of `使用Github来做`.

Reference: http://www.zhihu.com/question/19587406

**Comment by bryandeng** [comment]
@Psycho7

**Comment by Psycho7** [comment]
Nice to know that, do you wanna create a PR for this?

**Comment by bryandeng** [comment]
Yes, maybe after other content modifications are merged.

**Comment by jlevy** [comment]
There are tools for this, I think, e.g. the ones linked at https://github.com/vinta/paranoid-auto-spacing

**Comment by jlevy** [comment]
Lmk if this should be still open... Thanks!

**Comment by Psycho7** [comment]
@jlevy sorry...Idk how 'open' or 'closed' function...Not familiar with those...
