### ISSUE TITLE
Portuguese translation and maintainer

### ISSUE THREAD

**Issue by niltonvasques** [jlevy/the-art-of-command-line#130]

**Comment by jlevy** [comment]
:+1: Obrigado! Me avise quando tem uma versão completa. :)

**Comment by niltonvasques** [comment]
De nada! Assim que tiver finalizado aviso por aqui ;)

**Comment by niltonvasques** [comment]
Hi @jlevy, the work is done now! ;)

**Comment by jlevy** [comment]
:+1: Muito obrigado!
Appreciate if you can help keep it up to date and review PRs on the Portuguese one.

**Comment by niltonvasques** [comment]
Yeah! I can review portuguese PRs and keep it up to date as well!
