### ISSUE TITLE
key bindings

### ISSUE THREAD

**Issue by in4mer** [jlevy/the-art-of-command-line#14]
Please try to distinguish between normal, unixy key bindings (like ^U), and editor-specific key bindings, like ^K, ^A, and ^E.  There is little point to learning emacs key bindings for shellish things, when vi knowledge is another heavy prerequisite for modern administration.

**Comment by jlevy** [comment]
Not sure this entirely makes sense. For example, I am a heavy vi user, but prefer non-vi on the command line, and all the key-bindings like ctrl-a, ctrl-e etc work as part of readline, not as part of an editor. Type "man readline" and you'll see them all.

**Comment by michaelbarlow7** [comment]
You can use vi keybindings in bash by adding "set -o vi" to ~/.bash_rc.

I made a pull-request to add this to the page.

https://github.com/jlevy/the-art-of-command-line/pull/9

**Comment by jlevy** [comment]
set -o vi is now there. Resolving.
