### ISSUE TITLE
Typo about  glob expansion character [] 

### ISSUE THREAD

**Issue by gilleslamiral** [jlevy/the-art-of-command-line#146]
In section Basics:

`- Learn about file glob expansion with * (and perhaps ? and {...})`
`+ Learn about file glob expansion with * (and perhaps ? and [...])`

{} is for grouping commands.
[] is for file glob expansion.

**Comment by uggla** [comment]
Create a PR #260 to fix that.

**Comment by jlevy** [comment]
Fixed in #260
