### ISSUE TITLE
redirection of output and input, Appending Redirected Output, Here Documents

### ISSUE THREAD

**Issue by ox0spy** [jlevy/the-art-of-command-line#151]
see http://linux.die.net/man/1/bash REDIRECTION section.

The general format for appending output is:
   [n]>>word

 The format for appending standard output and standard error is:
              &>>word

This is semantically equivalent to
              >>word 2>&1

Here Documents, Here Strings ...

**Comment by ox0spy** [comment]
http://wiki.bash-hackers.org/syntax/redirection

**Comment by jlevy** [comment]
Here docs are already there, so I think this is now covered. If something else needs attention, file another issue. Thanks!
