### ISSUE TITLE
consider adding cls

### ISSUE THREAD

**Issue by xPetrus** [jlevy/the-art-of-command-line#158]
adding cls to clear a messy screen.

**Comment by ceoaliongroo** [comment]
Did you mean add how alias to `clear` command?. Like `alias cls=clear`.  

Already there is a comment about clear the screen with __ctrl+l__, under the section [Everyday use](https://github.com/jlevy/the-art-of-command-line#everyday-use)

**Comment by xPetrus** [comment]
Thank you, I must have missed that.
