### ISSUE TITLE
No manual entry for ascii in RedHat 6

### ISSUE THREAD

**Issue by netei** [jlevy/the-art-of-command-line#224]
Do you have anything to install to have access to `man ascii` ? Or is it distribution specific ?

**Comment by jlevy** [comment]
I've used it on Ubuntu. Will leave this open in case someone familiar with RedHat can comment.

**Comment by neuhaus** [comment]
Yes, both "man ascii" and "man latin1" work on RedHat 6 if you have the `man-pages` RPM installed.
"man latin1" will show the "iso_8859-1" manpage.

**Comment by netei** [comment]
Great ! Thanks.
