### ISSUE TITLE
Simple git coverage.

### ISSUE THREAD

**Issue by ShawnMilo** [jlevy/the-art-of-command-line#236]
For shell scripting, or manipulating data with shell scripting, git is extremely handy, even if only to recover accidentally altered files. Some basics would be good.

Also, since git is a command-line tool, many shortcuts can be taken for cleanups such as rebasing. If there's interest, I'll create a PR.

**Comment by Neirda24** [comment]
@ShawnMilo : I'm not sure we should really explain git here. Even basics. I agree it is very usefull but not needed in cli. Tell me if I'm wrong but the purpose of this repository is not to list every command available. Only those that will help people to master the cli and help them save a lot of time. One thing we could do is presenting a good config for git maybe ?

**Comment by ShawnMilo** [comment]
I think that if git is out of scope, then `.gitconfig` probably is as well. It makes sense to keep the primer focused.
