### ISSUE TITLE
 Use alt-b and alt-f to move by word?

### ISSUE THREAD

**Issue by pjbruce** [jlevy/the-art-of-command-line#245]
I try to use the two command in Terminal and find them can't move by word.  
The right command is ctrl-b and  ctrl-f.

**Comment by jlevy** [comment]
The doc is correct, but in Mac OS you need to enable the Option key as a meta key to get this to work. See the note I've just added to the doc to clarify.

ctrl-b and ctrl-f move by characters, not by words.
