### ISSUE TITLE
The dateutils conundrum

### ISSUE THREAD

**Issue by Hunter-Github** [jlevy/the-art-of-command-line#258]
There are four implementations dealing with date/time arithmetic, besides the obvious path of scripting them in (one's favortite language):

* https://github.com/hroptatyr/dateutils (last commit Aug 10, 2015, very active, probably the most likely candidate)
* http://sourceforge.net/projects/yest/ (Jul 29, 2014, slightly different feature set)
* https://github.com/alanfalloon/dateutils (last commit Dec 15, 2012, abandonware)
* http://www.eskimo.com/~scs/src/#dateexpr (last update in 2003)

@hroptayr's dateutils are packaged with ArchLinux, Debian, FreeBSD, Gentoo, NetBSD, OpenSuSE, OS X Homebrew, Slackware, Ubuntu.

Utilities included with the set:

*    `strptime` Command line version of the C function
*    `dateadd` Add durations to dates or times
*    `dateconv` Convert dates or times between calendars
*    `datediff` Compute durations between dates or times
*    `dategrep` Grep dates or times in input streams
*    `dateround` Round dates or times to “fuller” values
*    `dateseq` Generate sequences of dates or times
*    `datetest` Compare dates or times
*    `datezone` Convert date/times to timezones in bulk

`dateadd` and `datediff` seem to be the most useful items, with the rest worthy at most of a tiphat.

**Comment by jlevy** [comment]
Thanks for researching this.
It sounds like the right answer is to add a single one-line reference, something like: "For manipulating date and time expressions, see `strptime`, `dateadd`, `datediff`, etc. from dateutils."

If you'd like to add this as a PR, I'll merge it.

**Comment by uggla** [comment]
Yeah ! Really cool tools thanks @Hunter-Github for the info.
FYI, a package dateutils is available also on Fedora 22 (not listed on the website).
This is coming from http://www.fresse.org/dateutils / https://github.com/hroptatyr/dateutils
