### ISSUE TITLE
Change "du -sk" to "du -sh", better for humans

### ISSUE THREAD

**Issue by tombrus** [jlevy/the-art-of-command-line#26]
You mention `du -sk`, as a human I prefer `du -sh`.

:+1: Oh, and I love your write-up! ...still finding things to learn.

**Comment by Grimy** [comment]
I prefer `du -skc * | sort -n`. Human-readable output is nice, but not really pipe-friendly.

Ideally we would have a “humanify” or “hs” command, allowing us to do `du -sbc * | sort -n | hs`. That’s actually rather easy to implement: `alias hs='perl -pe "s;\d\K(\d{3})+\b;qw(k M G T P)[\$&=~y///c/3-1];e"'` will do the trick.

**Comment by tombrus** [comment]
For sorting you can use `-h` as well: `du -sh * | sort -h`.

Current Ubuntu at least, not supported on my Mac though :cry:

**Comment by Grimy** [comment]
Ooh, thanks, I didn’t know about `sort -h`. It’s not in POSIX, so I imagine it’s a GNU extension.

**Comment by tombrus** [comment]
Good to help! As said, there is always something to learn. These sort of write-ups are a great help for that, and fun to read! Thanks!

**Comment by jlevy** [comment]
:+1: Thanks @tombrus and all for the discussion. I think this is an improvement.
