### ISSUE TITLE
"grep ." to inspect a directory

### ISSUE THREAD

**Issue by dimo414** [jlevy/the-art-of-command-line#291]
There's a suggestion:

> Use `grep . *` to visually examine all contents of all files in a directory, e.g. for directories filled with config settings, like `/sys`, `/proc`, `/etc`.

At a glance, this could just as easily be `cat *` - is there something better about `grep .` that I'm missing?  And if this could be simplified to:

> Use `cat *` to output all the files in a directory.

I'm not sure what the point is.  `cat * | less` is *marginally* more helpful, but I don't think this suggestion is worth keeping - unless I'm missing something, in which case it'd be nice if that were made clearer.

**Comment by tim-teufel** [comment]
AFAIK, `cat *` shows no file names:
```bash
timur@r500:~/Downloads/tmp$ echo 'line 1' > a.txt
timur@r500:~/Downloads/tmp$ echo 'line 2' > b.txt
timur@r500:~/Downloads/tmp$ grep . *
a.txt:line 1
b.txt:line 2
timur@r500:~/Downloads/tmp$ cat *
line 1
line 2
```
So, `grep . *` is nice if you do not want to lump everything together.

**Comment by dimo414** [comment]
Ok, that's not terrible.  I'll send a PR to tweak the language, though.

**Comment by jlevy** [comment]
Exactly. It's a bit obscure, but it's definitely the easiest way to do this sometimes.
`head *` is another variant like this.
