### ISSUE TITLE
The version of teh rename command mentioned here isn't used on all distributions

### ISSUE THREAD

**Issue by jrobeson** [jlevy/the-art-of-command-line#296]
Quoting:
  `To rename many files at once according to a pattern, use rename. For complex renames, repren may help.`

I know it's in debian and their derivatives, but it's not the one available in util-linux. They rename the util-linux one to `/usr/bin/rename.ul` as seen here: https://packages.debian.org/squeeze/amd64/util-linux/filelist and replaced it with their own variant.  It should probably be marked as distribution specific and another alternative should be mentioned that works in a similar fashion (less complicated than repren).

**Comment by jlevy** [comment]
Yes, agreed, it's confusing even mentioning rename. What about adding a link to the Debian one and saying (if on Debian or other distros where available). Do you have a link to the right one to put there?

(And regarding repren, if you have feedback/suggestions on how to make it less complicated or confusing, [file an issue](https://github.com/jlevy/repren/issues) and I'll look at it. I'm biased of course but my intention is for that tool to be easier to use than any of the others.)

**Comment by jrobeson** [comment]
i've never used repren, I meant to write complex as that as the wording mentioned there.

**Comment by jrobeson** [comment]
I don't think this worlding solves it, because rename is always available, just not that one

**Comment by jlevy** [comment]
OK, hope that's better.
