### ISSUE TITLE
same content different effect with markdown

### ISSUE THREAD

**Issue by mudongliang** [jlevy/the-art-of-command-line#337]
I find a little problem, "apt-get" has the same form in English and Chinese edition, but different effect with markdown. The following two pictures is the screenshot from the source code:
![screenshot from 2016-01-07 16 10 31](https://cloud.githubusercontent.com/assets/6214861/12165500/7d37e934-b559-11e5-8132-0ce1e795329d.png)
![screenshot from 2016-01-07 16 11 06](https://cloud.githubusercontent.com/assets/6214861/12165502/7d3f9a9e-b559-11e5-9c0d-c34b7fbe2c77.png)
The different effect of markdown for "apt-get" is in the following screenshots:
![screenshot from 2016-01-07 16 08 12](https://cloud.githubusercontent.com/assets/6214861/12165499/7cef820c-b559-11e5-8b14-83d01a0805a3.png)
![screenshot from 2016-01-07 16 08 43](https://cloud.githubusercontent.com/assets/6214861/12165501/7d39b494-b559-11e5-8c40-8e34f92ca03d.png)
I don't know much about markdown. Maybe it's the markdown intepreter or what.

**Comment by tim-teufel** [comment]
Seems we want a [non-breakable in-line code block](http://stackoverflow.com/questions/20769127/non-breakable-inline-code-block-in-markdown-document) here. Or maybe a better solution is to reword that list of package managers to break them into separate words. The "/" character used there "glues" them together.

**Comment by jlevy** [comment]
Seems pretty minor, but sure, glad if anyone wants to PR to fix this. I'm with changing this to:

`apt-get`, `yum`, `dfn`, `pacman`, `pip`, or `brew`

**Comment by mudongliang** [comment]
Good idea to solve this problem.

**Comment by jlevy** [comment]
:+1: to @tim-teufel but that is for English only so this issue still isn't resolved -- need same updates to other translations.

**Comment by tim-teufel** [comment]
Well, that made me know a bunch of words meaning “or” in various languages as well as the strange punctuation in East Asian languages (they really have their own comma :open_mouth: ).
The huge help was that there is a similar list of package managers using commas and “or” just a bit later in the document. :wink:
