### ISSUE TITLE
Traditional Chinese translation

### ISSUE THREAD

**Issue by kevingo** [jlevy/the-art-of-command-line#349]
Hi, may I open an issue for Traditional Chinese translation ? 

I know there exist the version of Chinese version, but it is Simplified Chinese which is widely used in China. I want to do the Traditional Chinese version of this nice article.

**Comment by jlevy** [comment]
OK. The only issue is that it should be kept up to date. Are you able to maintain it as it evolves, too?
If so, sure, please review
https://github.com/jlevy/the-art-of-command-line/blob/master/CONTRIBUTING.md#translations
and file a PR.

**Comment by jlevy** [comment]
Thank you!

**Comment by kevingo** [comment]
No problem, it will be great. Thank you.

**Comment by RexYuan** [comment]
@kevingo 期待繁中的版本！

**Comment by kevingo** [comment]
@RexYuan 感謝，有問題隨時歡迎 PR

**Comment by kevingo** [comment]
@jlevy I found the filename naming rule is "file README-xx.md" and "xx" should be the standard two-letter ISO language codes. Currently the Chinese version is "README-zh.md". May I use "zh-tw" for Traditional Chinese since it is commonly use in the Chinese system.

Thank you.

**Comment by jlevy** [comment]
Please use "zh-Hant". This is the IETF language code and has the advantage of not confusing language and country. http://www.w3.org/International/articles/language-tags/

(We might switch the existing one to zh-Hans later, but leave it as is for now.)

Thanks for checking!

**Comment by kevingo** [comment]
OK

**Comment by Psycho7** [comment]
Looking forward to that :+1:
