### ISSUE TITLE
fr: Feedback on to translation

### ISSUE THREAD

**Issue by jlevy** [jlevy/the-art-of-command-line#351]
While I don't speak French, I've received the following suggestions from a friend who kindly reviewed #344.

@ericguirbal would you care to review/merge any of these in?
@uggla @rverchere perhaps you have thoughts too?

---

> Merci de contribuer si vous voyez une erreur ou quelque chose qui pourrait être meilleur !

Merci de contribuer si vous voyez une erreur ou une occasion d'éclaircir le texte.

> Ce guide est destiné aux débutants et aux utilisateurs chevronnés

Ce guide est destiné aux débutants comme aux utilisateurs chevronnés

> Les shells alternatives peuvent être intéressants

Les shells alternatifs peuvent être intéressants
(shell is masculine)

> Apprenez à rediriger les entrées et sorties au moyen de > et <, et à créer des tubes avec |

I think we use "pipe" in French as well, but I maybe behind the times on that one

> Si vous n'êtes pas sûr qu'il fera les bonnes choses, utilisez d'abord xargs echo

Si vous n'êtes pas sûr d'avoir fait ce qu'il faut, utilisez d'abord xargs echo

> Pour obtenir les permissions d'un fichier en octal, utile pour configurer le système mais non fournit pas ls

Pour obtenir les permissions d'un fichier en octal, utile pour configurer le système mais non fournit par ls

**Comment by ericguirbal** [comment]
> Merci de contribuer si vous voyez une erreur ou quelque chose qui pourrait être meilleur !
> > Merci de contribuer si vous voyez une erreur ou une occasion d'éclaircir le texte.

Ok.

> Ce guide est destiné aux débutants et aux utilisateurs chevronnés
>>  Ce guide est destiné aux débutants comme aux utilisateurs chevronnés

Ok.
 
> Les shells alternatives peuvent être intéressants
> > Les shells alternatifs peuvent être intéressants

Oups, I've choosen the wrong language :-)

> I think we use "pipe" in French as well, but I maybe behind the times on that one

The word "tube" is widely used in books or university courses. More generally, I think we should keep the english word if and only if it has no equivalent in french that is widely adopted. I also think it could be useful to give the english word for each translation of a technical term (the first time it is used in the guide).

>  Si vous n'êtes pas sûr qu'il fera les bonnes choses, utilisez d'abord xargs echo 
>  > Si vous n'êtes pas sûr d'avoir fait ce qu'il faut, utilisez d'abord xargs echo

Ok.

> Pour obtenir les permissions d'un fichier en octal, utile pour configurer le système mais non fournit pas ls
> > Pour obtenir les permissions d'un fichier en octal, utile pour configurer le système mais non fournit par ls

Ok.

Many thanks to your friend. I am willing to merge if he can't but what name must I use for the author ?

**Comment by jlevy** [comment]
My friend seems to prefer being anonymous. Use the suggestions however you see fit, in your own PR. :) Thanks!

**Comment by uggla** [comment]
@ericguirbal , I vote for :
"Merci de contribuer si vous voyez une erreur ou quelque chose que vous pourriez améliorer."
I would remove the exclamation mark at the end as well but that doesn't matter.

I confirm "tube" is fine as well, it doesn't shock me.

**Comment by ddavout** [comment]
Bonjour,  je profite de la présence de quelques fautes de frappe, pour vous remercier de votre travail à moins que cela ne soit le contraire

> Pour obtenir les permissions d'un fichier en octal, utile pour configurer le système mais non fournit par ls
**fourni** sans t final

> intéragir, intéractive
sans accent

**Comment by ddavout** [comment]
>  Utilisez `getfacl` et `setfacl` pour sauvegarder et restorer les permissions.

rest**au**rer

**Comment by ddavout** [comment]
extrèmement au liieu de extrêmement

**Comment by ericguirbal** [comment]
Merci @ddavout pour votre relecture. Le ticket étant fermé, il est préférable d'en ouvrir un nouveau pour signaler les erreurs. Encore mieux, vous pourriez proposer un *pull request* ^_^ Mon dernier *pull request* de l'été 2019 n'a toujours pas été pris en compte. Je viens de relancer. Patience donc ...

> extrèmement au liieu de extrêmement

L'adverbe s'écrit bien avec un accent circonflexe.
