### ISSUE TITLE
one command to handle "1.txt->001.txt,2.txt->002.txt,...99.txt->099.txt"

### ISSUE THREAD

**Issue by mudongliang** [jlevy/the-art-of-command-line#401]
I remember that one command can handle multiple files rename : "1.txt->001.txt,2.txt->002.txt,...99.txt->099.txt". Maybe it's rename of perl version. 
If you remember this trick, tell me please.
Thanks in advance.

**Comment by jlevy** [comment]
Take a look at https://github.com/jlevy/repren
It would be able to do this if you define all the mappings 1 -> 001 etc.
