### ISSUE TITLE
Obscure but useful: GNU datamash?

### ISSUE THREAD

**Issue by Hunter-Github** [jlevy/the-art-of-command-line#412]
For possible inclusion:

https://www.gnu.org/software/datamash/ - a handy replacement for a bunch of old-school 'cut|sort|seq|awk' pipelines for text files with tabular data

> GNU datamash is a command-line program which performs basic numeric,textual and statistical operations on input textual data files.

```
datamash groupby 1 countunique 3 <inputFile >outputFile
```
Also seems to run faster than chained textutils.

Status: mature at v.1.1.0. Maintained by Assaf Gordon.

**Comment by jlevy** [comment]
👍  Good addition, thanks!
