### ISSUE TITLE
Alternatives related to "a simple web server"

### ISSUE THREAD

**Issue by hartwork** [jlevy/the-art-of-command-line#425]
There are a number of alternatives to `python -m SimpleHTTPServer 7777` that may do a better job: easier and more powerful. The top three may be:
- gatling -- http://www.fefe.de/gatling/
- servefile -- https://github.com/sebageek/servefile
- pshs -- https://blogs.gentoo.org/mgorny/2014/12/26/pshs-the-awesome-file-sharing-tool/

**Comment by mkwardakov** [comment]
The aim here is not to run more powerful server.
And python is pre-installed.

**Comment by hartwork** [comment]
Closing to keep https://github.com/issues clean for myself…
