### ISSUE TITLE
Please point to -f with strace

### ISSUE THREAD

**Issue by hartwork** [jlevy/the-art-of-command-line#427]
Using strace without `-F` often ends up missing important calls. I would argue it is more often used with -F than without and finding the cause can be quite painful.

Thanks, Sebastian

**Comment by jlevy** [comment]
Sure. Would you be willing to make a small PR, adding a brief note about this?

Also I think `-f` is the standard flag name now.

Thanks!

**Comment by mkwardakov** [comment]
From man:

> -F          This option is now obsolete and it has the same functionality as -f.
