### ISSUE TITLE
Redo Windows only section to include information about bash on Windows when operating system is Windows 10

### ISSUE THREAD

**Issue by nexocentric** [jlevy/the-art-of-command-line#434]
https://www.youtube.com/watch?v=YzltJnhb61M

**Comment by peterkokot** [comment]
Hello, yes, IMHO it is quite a revolutionary feature. The pull request to update the Windows section is available here:
https://github.com/jlevy/the-art-of-command-line/pull/397

If there is anything missing or explained wrong, let me know...

**Comment by jlevy** [comment]
Believe this is now closed with #397. If anything is missing, please comment or open a new issue.
