### ISSUE TITLE
Coverage of PowerShell?

### ISSUE THREAD

**Issue by nexocentric** [jlevy/the-art-of-command-line#448]
Now that Powershell has been open sourced and it can be installed on Linux and Mac, is it part of the scope of the document or is this strictly bash? I believe there was some early talk about this, but that was before Powershell was cross platform.

[Powershell Goes Open Source](http://www.techworm.net/2016/08/microsoft-open-sourcing-powershell-linux-mac-os-x.html)
[Installing Powershell on Linux](http://www.howtogeek.com/267858/how-to-install-microsoft-powershell-on-linux-or-os-x/)

**Comment by jlevy** [comment]
It's a good question. As usual, I think the answer is driven by quality of the content and what is helpful to readers.

I certainly can't do it, so I think the answer has to be "no" until we have both enough good content and a committed maintainer/owner for PowerShell. If we had both, we could perhaps have a PowerShell section. If anyone is interested, I suggest they write a first draft of that section and share it, and we can see if it fits with this project, or is better on its own (with a link from here).

In the meantime, it's probably worth mentioning the existence of open source cross platform PowerShell in the Windows section? Further thoughts welcome. @dspinellis or other Windows experts?

**Comment by jlevy** [comment]
Incidentally, for those seeking drama and intrigue, GitHub offers us great summertime reading on this subject. ;)
https://github.com/PowerShell/PowerShell/pull/1901

**Comment by dspinellis** [comment]
PowerShell and its open-sourcing is an interesting development, but I don't think it has a place in this document. It uses a different syntax and IPC mechanism than a traditional Unix shell environment and therefore an extensive treatment of it here would only confuse users.

We can list it in a small section presenting alternatives together with e.g. csh and ksh as shells and Rexx, Perl, Python, Ruby, Groovy as scripting languages.

**Comment by neil-greenwood** [comment]
I agree with dspinellis. At most a small section.

**Comment by nexocentric** [comment]
If Python and Ruby are listed as scripting languages, it makes sense to list it as a scripting language. It might also make sense to list it as an alternative shell (once again in a small section).

I really can't say much as to how it runs on Linux since I haven't used it there yet. Since it's in alpha status, I might not touch it on Linux for a while.

**Comment by jlevy** [comment]
Added an issue to track @dspinellis 's suggestion, which I think is a good one. Comments/suggestions/PRs there welcome.

I'm fine closing this issue. (Anyone who wants to document PowerShell in greater depth can do it separately and let us know.)

**Comment by Andr3sC** [comment]
I agree with @dspinellis, small reference in a section with all the other alternatives. But I guess that first Power Shell should prove it usefulness.
