### ISSUE TITLE
Romanian Translation

### ISSUE THREAD

**Issue by mihaimaruseac** [jlevy/the-art-of-command-line#472]
I'm planning to add a translation for the guide in Romanian language.

I was born in Romania, lived there for 25 years and then I moved to the States for PhD. I still speak Romanian as my mother language and I can be a maintainer for this language in the future.

I expect to submit a PR in a few hours with the initial translation.

**Comment by jlevy** [comment]
That's great! Will look for it. If you know any other Romanian speaker who you can invite to review that is always helpful.

**Comment by mihaimaruseac** [comment]
Sure, I'll try getting other people to contribute too.
