### ISSUE TITLE
Organize the Windows-only section

### ISSUE THREAD

**Issue by dspinellis** [jlevy/the-art-of-command-line#477]
The "Windows only" section has degenerated into an disorganized grab-bag of useful stuff.  I suggest we organize it into:
- Ways to obtain Unix tools under Windows
- Windows CLI commands worth knowing
- Cygwin tips and tricks

**Comment by dtsdwarak** [comment]
Pull request updated as per the issue tasks.

**Comment by dspinellis** [comment]
I intended to do this organization myself and I was therefore not clear enough.  This is what I propose.

###    Ways to obtain Unix tools under Windows
Cygwin, Bash on Ubuntu, mingw, Cash

###    Useful CLI Tools for **nix** utilities
Chocolatey and wmic

###    Cygwin tips and tricks
The rest plus regtool (it is part of Cygwin).

**Comment by jlevy** [comment]
As maintainer of that section would be glad to see you organize this how you see fit @dspinellis if you want to revisit this again! :)
