### ISSUE TITLE
Grep alternatives: Better overview/links on ag, rg, etc.

### ISSUE THREAD

**Issue by almereyda** [jlevy/the-art-of-command-line#485]
The TAO already mentions to use `ag` over `grep`.
I suggest to consider replacing it with [`rg`](https://github.com/BurntSushi/ripgrep).

See where this can lead at https://medium.com/@crashybang/supercharge-vim-with-fzf-and-ripgrep-d4661fc853d2#.lmu6qvggt

**Comment by mkwardakov** [comment]
Ripgrep is not yet included to major distributives repositories.

**Comment by jlevy** [comment]
Agree, good idea. I think given there are several items like this, we have to mention the major ones (for context). Focused PR on this welcome!

**Comment by jlevy** [comment]
Another post: http://blog.burntsushi.net/ripgrep/

**Comment by jlevy** [comment]
Have listed all three given each is known by different people. If anyone thinks there is more to add, please drop a note here or add a new issue for new commands.
