### ISSUE TITLE
Explanation

### ISSUE THREAD

**Issue by E3D3** [jlevy/the-art-of-command-line#508]
Giving advice without any explanation doesn't make sense. For example in the section 'Basics' it advices to learn ssh, basic network management and version control management system, things I explored but never needed or used last 20 years. A CLI-artist  is not the same as an system administrator, and doesn't require learning tools you never need. Maybe adding at least one line with a reason why people should learn something would be helpfull.

**Comment by E3D3** [comment]
Adding to my previous issue/remark:

I also advice things that helped me learning:

Easy searching info, essential to avoid overwhelming by the huge amount of info:
-  [marker](https://github.com/pindexis/marker) lets you bookmark commands (or commands templates) and easily retreive them with the help of a real-time fuzzy matcher.
- [cheat](https://github.com/chrisallenlane/cheat) allows you to create and view interactive cheatsheets on the command-line.
- Using zsh shell completion system, e.g. for easy access to possible command options.
- Using Emacs text editor because it has info, man, shells and more within reach of  a few keystrokes, (I don't know how to sell this point without editor flame war.)
- Reading man-pages in a webbrowser for more readablility, links and sections-overview.
- To learn Bash it is wise to follow the advice give on IRC chat freenode channel #bash and start by using their advised tutorials and reference.
- and similar tips from other 'advanced beginners'.

Also very important is to warn beginners that there’s a whole rabbit hole of internet pedantry you can tumble into.

**Comment by jlevy** [comment]
Thanks @E3D3 for the extensive thoughts.

This issue covers a lot of ground, and I can't address all of it realistically with general suggestions. For each of these points, very small, focused changes (in separate PRs) are very welcome. I've added two issues to track marker and chat, which I definitely agree should be mentioned.

Other items that are more contextual or opinion-based are welcome too, but take more time to write in a careful way. If you want to work to suggest wording on any one of these, please file an individual PR for it. Thanks again!
