### ISSUE TITLE
random tip function taocl() also gives an error

### ISSUE THREAD

**Issue by pr4j** [jlevy/the-art-of-command-line#533]
In the function taocl(), pandoc creates a tag "figure" and xmlstarlet is unable to format that tag and ends up printing the following error along with the random tip:
```
-:18.8: Tag figure invalid
<figure>
       ^
-:19.188: Tag figcaption invalid
<99> | egrep -o â<80><98>\w+â<80><99> | tr -d â<80><98>`â<80><99> | cowsay -W50" /><figcaption
```
I couldn't get around avoiding the error altogether, so to stop it from printing the error, I'm just redirecting the stderr.

**Comment by ResponSySS** [comment]
A temporary workaround (just remove the line containing 'cowsay.png') is `sed '/cowsay[.]png/d` after downloading the page.  
I also get formatting errors like in:
```
$ taocl.sh  
Brace expansion using {â¦} can [...]
```
That's why I have added the `iconv -t US` which resolves this issue.

```
function taocl() {
        curl -s https://raw.githubusercontent.com/jlevy/the-art-of-command-line/master/README.md |
          sed '/cowsay[.]png/d' |
          pandoc -f markdown -t html |
          xmlstarlet fo --html --dropdtd |
          xmlstarlet sel -t -v "(html/body/ul/li[count(p)>0])[$RANDOM mod last()+1]" |
          xmlstarlet unesc | fmt -80 | iconv -t US
      }
```

**Comment by jlevy** [comment]
Hm, works for my version of those tools but this seems like a more robust option, so sure.
Thanks @ResponSySS and @pr4j !
