### ISSUE TITLE
update README-ja.md

### ISSUE THREAD

**Issue by CoffeeTakada** [jlevy/the-art-of-command-line#566]
I've noticed that the Japanese version of README has not been modified for a while, and some of the explanations are incomplete. So I decided to update README-ja.md based on the original.

Currently, I'm working on Here. I will create a pull request when it's done.
https://github.com/jlevy/the-art-of-command-line/compare/master...koh7:master

**Comment by doublemarket** [comment]
@jlevy This can be closed because you've merged #568. Thanks!
