### ISSUE TITLE
Trying to understand why shell behaves the way it is behaving

### ISSUE THREAD

**Issue by a07r** [jlevy/the-art-of-command-line#576]
I guess, I would be happy, had the system threw me an error/warning. But it some how seems to put a logic of it's own and gives me a result. Can anyone please help me understand what logic it's following? 

[XYZ@oc ~]$ q=2
[XYZ@oc ~]$ q=$(( q+=1 | $q % 10 ))
[XYZ@oc ~]$ echo $q
5
[XYZ@oc ~]$ q=$(( q+=1 | $q % 10 ))
[XYZ@oc ~]$ echo $q
10
[XYZ@oc ~]$ q=$(( q+=1 | $q % 10 ))
[XYZ@oc ~]$ echo $q
11
[XYZ@oc ~]$ q=$(( q+=1 | $q % 10 ))
[XYZ@oc ~]$ echo $q
12

**Comment by tim-teufel** [comment]
You should run `man bash` and read there sections called "Arithmetic Expansion" and "ARITHMETIC EVALUATION".
Let's decompose your expression: `$(( q+=1 | $q % 10 ))` reads "Add to the variable's current value the result of `1 | $q % 10`, that is 1 bitwise ORed with the remainder in division `$q` by 10".
Check for yourself now that the calculations are correct.

**Comment by tim-teufel** [comment]
> this result 2 is bitwise ORed with 1 to give me 3 (in decimal)

Yep, so we got `$(( q+= 3 ))`, which reads "add 3 to the variable's current value". The value of `q` was 2, hence `q = 2 + 3`, that is 5. Right?

> I don't know how do I deal with bitwise OR and "+=" together cause preference favors bitwise OR but if I do just that then I am not left with an operand for "+="

The `+=` operator in `$(( q+=1 | $q % 10 ))` has two operands, `$q` and the result of the expression on the right-hand side.

**Comment by a07r** [comment]
@tim-teufel thanks makes sense, but only after you spoon fed me.. thanks a lot for your time!

**Comment by tim-teufel** [comment]
OK, good. How about closing this ticket, then? 😉

**Comment by a07r** [comment]
Yes sure
