### ISSUE TITLE
adding glances for system debugging section

### ISSUE THREAD

**Issue by simar7** [jlevy/the-art-of-command-line#6]
[glances](https://github.com/nicolargo/glances) is a very nifty tool that incorporates many other tools like htop, network status, sensor status, etc. into one simple and powerful utility. I'd think it'd be a good addition to this guide!

**Comment by simar7** [comment]
lmk if you're interested and I can submit a PR!

**Comment by jlevy** [comment]
Yeah, thanks. How about we add it alongside dstat.

**Comment by simar7** [comment]
cool, submitted a PR: https://github.com/jlevy/the-art-of-command-line/pull/18
