### ISSUE TITLE
Vietnamese Translation

### ISSUE THREAD

**Issue by DukeNgn** [jlevy/the-art-of-command-line#606]
I would like to contribute Vietnamese language version to your project. My mother tongue is Vietnamese language and I have been living in Canada for 2 years, fluent in English. I could be maintainer if needed.
I have read your contributing guidelines about this project so just filing this issue to announce I am in progress for Vietnamese Translation. 
Thank you.

**Comment by rockmanvnx6** [comment]
Hey @DukeNgn how is the progress going. I'm interested in contributing to this.

**Comment by DukeNgn** [comment]
@rockmanvnx6 Sorry, I got carried away and currently don't have the bandwidth to finish the task. I'm closing the issue for now. If you're interested, please open a new issue. Thanks!
