### ISSUE TITLE
Everyday use, may want to mention vi mode

### ISSUE THREAD

**Issue by pshahid** [jlevy/the-art-of-command-line#61]
At the top of every day use there's an example of several keyboard shortcuts for deleting words and erasing the line. That's in the emacs cli mode, which is the default, but you can also use the vi mode. This allows you to use the vi macros for navigation, which can be much more fluid when the user is accustomed to vi or vim. Just an idea!

**Comment by jlevy** [comment]
Agree. Closing as dup of #9 . Thanks.
