### ISSUE TITLE
Some markdown bold syntax is incorrectly displayed in README-ko.md

### ISSUE THREAD

**Issue by 9w** [jlevy/the-art-of-command-line#651]
Some markdown bold syntax is incorrectly displayed.
- 예를 들면 **alt-.**같은 경우
- ctrl-v **[Tab]**키를 누르거나

It should be modified as follows.
- 예를 들면 **alt-.** 같은 경우
- ctrl-v **[Tab]** 키를 누르거나

**Comment by rive23** [comment]
Helow maa'm

**Comment by nuttapon2532** [comment]
https://m.bacc6666.com/UI/V1/GameLobby.aspx?type=1&gameid=

**Comment by kuailekai-1727** [comment]
windows........

**Comment by kuailekai-1727** [comment]
https://github.com/

**Comment by vicobill** [comment]
ha? if you need help, please use international language:ENGLISH :)
