### ISSUE TITLE
Awk one-liner duplicates an earlier example

### ISSUE THREAD

**Issue by dimo414** [jlevy/the-art-of-command-line#67]
In "Processing files and data":

> Know basic `awk` and `sed` for simple data munging. For example, summing all numbers in the third column of a text file: `awk '{ x += $3 } END { print x }'`. This is probably 3X faster and 3X shorter than equivalent Python.

In "One-liners":

> - Summing all numbers in the third column of a text file (this is probably 3X faster and 3X less code than equivalent Python):
> 
> ``` sh
>       awk '{ x += $3 } END { print x }' myfile
> ```

**Comment by crr0004** [comment]
Is there something wrong? I am unsure what you're trying to say

**Comment by dimo414** [comment]
Well, it seemed strange to me that the same example is in two places.  If that's intentional and desirable, this can be closed.
