### ISSUE TITLE
Add a License

### ISSUE THREAD

**Issue by JohnCassavetes** [jlevy/the-art-of-command-line#716]
Public repositories on GitHub are often used to share open source software. For your repository to truly be open source, you'll need to license it so that others are free to use, change, and distribute the software. Here are just some to choose from:
-  the MIT License `mit`
- GNU General Public License v3.0 `gpl-3.0`
- Creative Commons license family `cc`

The full link to GitHub's ['Licensing a repository'](https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/licensing-a-repository)

**Comment by toydotgame** [comment]
![image](https://user-images.githubusercontent.com/64190512/117279771-6444cf00-aea5-11eb-9b5e-b1d6d07903e6.png)
?

**Comment by jlevy** [comment]
License is on the doc.
