### ISSUE TITLE
Remove fortune, ddate, and sl

### ISSUE THREAD

**Issue by hastinbe** [jlevy/the-art-of-command-line#75]
I propose removing `fortune`, `ddate`, and `sl` commands due to their limited usefulness, and having nothing to do with the ideology of The Art of Command Line.

**Comment by crr0004** [comment]
They're in the obscure section and I think it's a good thing to have them in there, even just for the cultural learning of Linux.

**Comment by hastinbe** [comment]
I have to disagree. Every note and tip here is to be essential or useful in some way.

**Comment by deavmi** [comment]
`cowsay This command is awesome.`

**Comment by jlevy** [comment]
As mentioned in #70, I'm not interested in lots of games/diversions, but these few are so old/classic I think they make the cut. Fortune can actually be used in useful ways.

Thanks for the suggestion though.

**Comment by hastinbe** [comment]
The scope section of this "the art of command line" should be updated to include "useless but historic commands"
