### ISSUE TITLE
add

### ISSUE THREAD

**Issue by nerdfiles** [jlevy/the-art-of-command-line#753]
- [ ] tmux and tmux-plugins (https://github.com/tmux-plugins/list),
- [ ] lazydocker, 
- [ ] todo.txt, 
- [ ] ack, 
- [ ] html-xml-utils, 
- [ ] unified-alps, 
- [ ] stoplight, 
- [ ] some validators[0], 
- [ ] alder (https://github.com/aweary/alder), 
- [ ] tig, 
- [ ] vim_cubed, 
- [ ] fzf and fd (https://github.com/junegunn/fzf https://mike.place/2017/fzf-fd/),
- [ ] vim-seek, 
- [ ] vim-surround, 
- [ ] gti,
- [ ] httrack,
- [ ] lynx, 
- [ ] links, 
- [ ] urlview, 
- [ ] irssi, 
- [ ] newsboat,
- [ ] ranger,
- [ ] basics and workflows[1],
- [ ] diceware and blackjack or dining philosophers or byzantine generals?,
- [ ] mutt,
- [ ] cmus,
- [ ] frotz (http://www.ifarchive.org/indexes/if-archive.html),
- [ ] cygwin (https://blog.miguelgrinberg.com/post/web-development-on-windows-does-not-need-to-suck),
- [ ] yeoman/yo,
- [ ] yUML (e.g., yEd2kingly),
- [ ] gruntjs,
- [ ] gulpjs,
- [ ] pm2,
- [ ] nodemon,
- [ ] almond/r.js,
- [ ] docker-compose,
- [ ] wp-cli,
- [ ] ng (angularAMD, https://angular.io/guide/testing-code-coverage, etc.),
- [ ] sirv (https://www.npmjs.com/package/sirv-cli),
- [ ] surge.sh,
- [ ] heroku, 
- [ ] netlify?,
- [ ] storybook?,
- [ ] node-red?,
- [ ] npx,
- [ ] npm (e.g., `> $(npm run | percol`)[3]),
- [ ] mongod,
- [ ] protractor,
- [ ] cucumber,
- [ ] cypress,
- [ ] jest (hydration),
- [ ] karma,
- [ ] glances,
- [ ] django,
- [ ] tornado  (https://www.tornadoweb.org/en/stable/options.html),
- [ ] nginx,
- [ ] apache,
- [ ] owasp zap (https://www.zaproxy.org/docs/desktop/cmdline/),
- [ ] ps,
- [ ] ghostscript, 
- [ ] `magick mogrify -resize NN% file.png`,
- [ ] convert,
- [ ] brew,
- [ ] curses (https://github.com/thobbs/multitail-curses),
- [ ] calcurse (https://opensource.com/article/18/10/calcurse),
- [ ] etcd,
- [ ] clusterluck,
- [ ] pandoc (specifically slideshow building),
- [ ] openchain,
- [ ] holochain (zomes),
- [ ] handshake wallets,
- [ ] nix (https://nixos.wiki/wiki/Nix_Installation_Guide),
- [ ] zsh,
- [ ] fish shell,
- [ ] jsdoc,
- [ ] css-specificity,
- [ ] jekyll  (https://pmarsceill.github.io/just-the-docs/#getting-started),
- [ ] gem,
- [ ] ctags,
- [ ] mosh,
- [ ] iptables,
- [ ] winston (https://github.com/winstonjs/winston/tree/2.x#using-winston-in-a-cli-tool), 
- [ ] wiredep (https://github.com/taptapship/wiredep-cli), 
- [ ] webpack (is this zuckerbug's?),
- [ ] qemu,
- [ ] cli's for load balancers, facades, circuit breakers, gateways, etc.,
- [ ] ionic (capacitor),
- [ ] android studio,
- [ ] consul,
- [ ] keyware cli to cache invalidate semantic keyed links for MRUs,
- [ ] etc.[2]

___ 

[0] ![ext_138_image1.jpg](https://user-images.githubusercontent.com/102306/147171466-0ae934fe-e42b-45fa-9da3-8a26ca710282.jpg), lighthouse, or
[1]: https://github.com/nerdfiles/Hybrid.AngularAMD.HATEOAS/blob/master/resources/grunt-default.png
[2]: https://github.com/nerdfiles/oh-my-grid/blob/master/package.json#L6-L34
[3] `aliases: run, rum, urn`

**Comment by nerdfiles** [comment]
also the screenshot has various duplicates lol

**Comment by jlevy** [comment]
Not following this issue. Closing.
