### ISSUE TITLE
A typo in README-zh.md

### ISSUE THREAD

**Issue by ftakanashi** [jlevy/the-art-of-command-line#759]
at Line. 195
The original text:
```
- 将 shell 切换为其他用户，使用 `su username` 或者 `sudo - username`。加入 `-` 会使得切换后的环境与使用该用户登录后的环境相同。省略用户名则默认为 root。切换到哪个用户，就需要输入_哪个用户的_密码。
```

`su - username` is incorrectly typed as `sudo - username`.
A little mistake though, might cause confusion towards beginners.

**Comment by Debaditya-Som** [comment]
Translated and corrected text of line 195 should be : 
`For switching the shell to another user, use `su username` or `su - username`. The latter with "-" gets an environment as if another user just logged in. Omitting the username defaults to root. You will be asked for the password _of the user you are switching to_.`

Corrected text : 
`将 shell 切换为其他用户，使用 `su username` 或者 `su - username`。加入 `-` 会使得切换后的环境与使用该用户登录后的环境相同。省略用户名则默认为 root。切换到哪个用户，就需要输入_哪个用户的_密码。`

I have seen this component of the repo and someone has merged a PR regarding this issue so you may close this issue

**Comment by ftakanashi** [comment]
OK. Thx for the remind.
