### ISSUE TITLE
somi khan

### ISSUE THREAD

**Issue by Somikhan123** [jlevy/the-art-of-command-line#770]
pkg update -y
pkg upgrade -y
pkg install git -y
pkg install python -y
pkg install python2 -y
python3 -m pip install --upgrade pip
pip install requests
pip install mechanize
pip install future
rm -rf somi
git clone https://github.com/somiking/somi.git
cd somi
python somi.py

**Comment by 1c3f1r3abc** [comment]
Password and username

**Comment by 1c3f1r3abc** [comment]
Please

**Comment by henriquecarlos2021** [comment]
Não quero receber mais notificações do Github pfv

Em seg, 2 de mai de 2022 22:13, 1c3f1r3abc ***@***.***>
escreveu:

> Please
>
>
