### ISSUE TITLE
dtach: Page not found

### ISSUE THREAD

**Issue by 532910** [jlevy/the-art-of-command-line#798]
https://github.com/bogner/dtach

**Comment by jlevy** [comment]
dtach is already mentioned. and that link doesn't look correct, so closing.

**Comment by 532910** [comment]
the mention is the broken link

**Comment by karfau** [comment]
so is there a link that works?

**Comment by 532910** [comment]
I dunno, just google.

I don't know what dtach is. Just noticed that the link is broken.

**Comment by 532910** [comment]
Reopen until fixed, please.
