### ISSUE TITLE
Please consider adding a license  

### ISSUE THREAD

**Issue by pearcej** [jlevy/the-art-of-command-line#800]

**Comment by cybernet** [comment]
why ?

**Comment by HenrikBengtsson** [comment]
> why ?

If, for example, the current copyright holders, stop maintaining this repo, then this effort my die out.  With a proper license, it makes it clear that others are allowed to fork it and keep working on it elsewhere.

**Comment by HenrikBengtsson** [comment]
That said, this is a duplicate of #716, which points out that the README has a License section (<https://github.com/jlevy/the-art-of-command-line#license>). The license is "CC BY-SA 4.0".

This can be closed

**Comment by pearcej** [comment]
Thanks!
