### ISSUE TITLE
Chinese translation and maintainer

### ISSUE THREAD

**Issue by Psycho7** [jlevy/the-art-of-command-line#82]
I'm willing to do this if it is needed :smiley:

**Comment by crr0004** [comment]
+1

Having translation is always a good thing

**Comment by jlevy** [comment]
Sure. Would be glad for this, especially if you can work with me a bit to keep it up to date and of high quality.

Was trying to think of the best approach, as I think having this guide fragmented across many out-of-sync repos isn't ideal.

So: How about we keep using this repo, and you submit a PR adding a new file entirely, called `README-zh.md`? This would then scale to other languages as well (abbreviations being the standard ones, as with https://en.wikipedia.org/wiki/List_of_Wikipedias ).

**Comment by jlevy** [comment]
I'd also appreciate anyone commenting on if they would use this in other languages. It's of course wonderful in principle, but it's also inevitable English will be most heavily edited and others will lag a bit (just as with Wikipedia).

**Comment by felixinx** [comment]
I will used it in french. I will work on the `README-fr.md` file.

Maybe you can change the title to 'Multilingual support`?

**Comment by Psycho7** [comment]
I will work on the *README-zh.md* file.

**Comment by jlevy** [comment]
:+1:

**Comment by Psycho7** [comment]
README-zh.md is finished and up-to-date now #94

**Comment by jlevy** [comment]
@felixinx I've created #99 to track your suggestion. I think one issue per language is appropriate.

**Comment by jlevy** [comment]
I also think it's important to have one person who will agree to keep it in sync and maintain it as it evolves.

Thanks again @Psycho7 !

**Comment by jlevy** [comment]
https://github.com/xuxiaodong has done the same thing for https://github.com/alebcay/awesome-shell/

Mentioning here since you both may be able to help each other review the translations and keep them up to date.

See https://github.com/alebcay/awesome-shell/pull/84

**Comment by Psycho7** [comment]
The translation I made still need refining, I will improve its quality in next few weeks. As for maintaining, it's not hard to keep it in sync with the help of `diff` and I will do this work regularly.

**Comment by jlevy** [comment]
Awesome. Keep the PRs coming. :)
