### ISSUE TITLE
Consider adding fzf

### ISSUE THREAD

**Issue by jlevy** [jlevy/the-art-of-command-line#96]
https://github.com/junegunn/fzf

**Comment by junegunn** [comment]
:+1: probably because I'm the maintainer of the project :)
The article already mentions [percol](https://github.com/mooz/percol), so I think it makes sense to suggest fzf as an alternative to it.

**Comment by deathmaz** [comment]
+1

**Comment by jlevy** [comment]
Agreed. Thanks for the cool utility! :)

**Comment by junegunn** [comment]
Great, thanks!
