### ISSUE TITLE
French translation and maintainer

### ISSUE THREAD

**Issue by jlevy** [jlevy/the-art-of-command-line#99]
Discussed at https://github.com/jlevy/the-art-of-command-line/issues/82

**Comment by felixinx** [comment]
I will translate and maintain a README for the french version of the art of command line.

**Comment by felixinx** [comment]
[Here is the first version](https://github.com/felixinx/l-art-de-la-ligne-de-commande/blob/master/README-fr.md), I don't have finished, so I didn't make a pull request.

**Comment by jlevy** [comment]
:+1: Thanks for starting. I'll look at the PR when it is ready.

**Comment by ericguirbal** [comment]
Argh! I submitted PR #344 and I just noticed @rverchere is working on a translation elsewhere (issue #102).

**Comment by jlevy** [comment]
Done in #344
